services:
  smart:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    ports:
      - "8000:8000"


  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:8000"
    environment:
      NGROK_AUTHTOKEN: 2lTdPoWwaWEaxrgl8Jr0p4E7Rnk_44vMgHsR5VPMAVn8N1eMY
    ports:
      - 4040:4040