services:
  smart:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres_url
      - LOCO_ENV=development
      - PLAID_ENV=production
      - PLAID_CLIENT_ID=client_id
      - PLAID_SECRET=secret
      - PLAID_VERSION=2020-09-14
    depends_on:
      - postgres
    ports:
      - "80:80"


  postgres:
    image: postgres:15.3-alpine  # You can specify the version of PostgreSQL
    container_name: postgres_reach
    environment:
      POSTGRES_USER: loco       # Change this to your preferred username
      POSTGRES_PASSWORD: loco  # Change this to your preferred password
      POSTGRES_DB: reach     # The database to be created
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data to a named volume

volumes:
  postgres_data: